### ISSUE TITLE
DecryptWithChecksum 方法有问题

### ISSUE THREAD

**Issue by mahong2010** [gxchain/gxclient-csharp#1]
string to = AES.DecryptWithChecksum(pk,pubKey ,nonce ,hexMsg);
在调用这个方法时，不能得到memo标签结果，报了以下异常：
Invalid checksum, expected d83ccd92, got efbfbdef
开始我是解析火币转进来的交易记录，现在我直接用网页版钱包发币，再解析，还是报上面那个错误。

**Comment by lanhaoxiang** [comment]
fixed via 5d215be2efad4c899872e8abc2411bbe0b9923d1

**Comment by lanhaoxiang** [comment]
@mahong2010 please provide your GXC account here

**Comment by mahong2010** [comment]
My GXC account:
mahong1




------------------ 原始邮件 ------------------
发件人: "Lan, Haoxiang"<notifications@github.com>;
发送时间: 2019年4月28日(星期天) 晚上8:52
收件人: "gxchain/gxclient-csharp"<gxclient-csharp@noreply.github.com>;
抄送: "浪子"<272536180@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [gxchain/gxclient-csharp] DecryptWithChecksum 方法有问题 (#1)




@mahong2010 please provide your  GXC account here
